version: 2.1

jobs:
  build:
    working_directory: ~/simpledb
    docker:
      - image: circleci/golang:1.14.6
    steps:
      - checkout
      - run:
          name: Run tests
          command: go test -coverprofile coverage.out -covermode atomic ./...
